name: main
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write
  packages: write

env:
  ASPNETCORE_ENVIRONMENT: Production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: restore
      run: dotnet restore

    - name: build
      run: dotnet build --configuration Release --no-restore

  unit:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
    - name: setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
      
    - name: test
      run: dotnet test -c Development test/Unit /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Upload coverage reports
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  push:
    runs-on: ubuntu-latest
    needs: [unit]
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup
      uses: docker/setup-buildx-action@v3

    - name: login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build and push
      uses: docker/build-push-action@v6
      with:
        tags: ghcr.io/jezielmoura/healthmed:${{ github.sha }}
        context: .
        push: true
